/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const AssetMetadata = IDL.Record({
  'assetId' : IDL.Text,
  'description' : IDL.Text,
  'assetType' : IDL.Text,
});
export const Time = IDL.Int;
export const Project = IDL.Record({
  'id' : IDL.Text,
  'projectName' : IDL.Text,
  'owner' : IDL.Principal,
  'inputAssets' : IDL.Vec(AssetMetadata),
  'createdAt' : Time,
  'outputAssets' : IDL.Vec(AssetMetadata),
  'updatedAt' : Time,
  'preset' : IDL.Text,
  'toolType' : IDL.Text,
  'configuration' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteProject' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProject' : IDL.Func([IDL.Text], [Project], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveProject' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(AssetMetadata),
        IDL.Vec(AssetMetadata),
      ],
      [IDL.Text],
      [],
    ),
  'updateProjectText' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const AssetMetadata = IDL.Record({
    'assetId' : IDL.Text,
    'description' : IDL.Text,
    'assetType' : IDL.Text,
  });
  const Time = IDL.Int;
  const Project = IDL.Record({
    'id' : IDL.Text,
    'projectName' : IDL.Text,
    'owner' : IDL.Principal,
    'inputAssets' : IDL.Vec(AssetMetadata),
    'createdAt' : Time,
    'outputAssets' : IDL.Vec(AssetMetadata),
    'updatedAt' : Time,
    'preset' : IDL.Text,
    'toolType' : IDL.Text,
    'configuration' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteProject' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProject' : IDL.Func([IDL.Text], [Project], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveProject' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(AssetMetadata),
          IDL.Vec(AssetMetadata),
        ],
        [IDL.Text],
        [],
      ),
    'updateProjectText' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };