export type ToolInputMode = 'generation' | 'edit' | 'hybrid';

export interface ToolDefinition {
  id: string;
  name: string;
  path: string;
  description: string;
  category: string;
  inputMode: ToolInputMode;
  icon: string;
}

export const TOOL_CATEGORIES = [
  'Design & Branding',
  'Photo Enhancement',
  'Creative Effects',
  'Event & Portrait',
  'Professional',
] as const;

export const TOOLS: ToolDefinition[] = [
  {
    id: 'logo-maker',
    name: 'Logo Maker',
    path: '/tools/logo-maker',
    description: 'Create professional logos with customizable styles and layouts',
    category: 'Design & Branding',
    inputMode: 'generation',
    icon: 'Sparkles',
  },
  {
    id: 'mockup-creator',
    name: 'Mockup Creator',
    path: '/tools/mockup-creator',
    description: 'Place your designs on realistic product mockups',
    category: 'Design & Branding',
    inputMode: 'hybrid',
    icon: 'Box',
  },
  {
    id: 'mini-world-generator',
    name: 'Mini World Generator',
    path: '/tools/mini-world-generator',
    description: 'Generate miniature world scenes with tilt-shift effects',
    category: 'Creative Effects',
    inputMode: 'generation',
    icon: 'Globe',
  },
  {
    id: 'barbershop-stylist',
    name: 'Barbershop Stylist',
    path: '/tools/barbershop-stylist',
    description: 'Try different hairstyles and facial hair styles',
    category: 'Event & Portrait',
    inputMode: 'edit',
    icon: 'Scissors',
  },
  {
    id: 'outpainting',
    name: 'Outpainting',
    path: '/tools/outpainting',
    description: 'Extend your images beyond their original boundaries',
    category: 'Creative Effects',
    inputMode: 'edit',
    icon: 'Maximize2',
  },
  {
    id: 'pov-hand-creator',
    name: 'POV Hand Creator',
    path: '/tools/pov-hand-creator',
    description: 'Add realistic first-person perspective hands to scenes',
    category: 'Creative Effects',
    inputMode: 'hybrid',
    icon: 'Hand',
  },
  {
    id: 'background-removal',
    name: 'Background Removal',
    path: '/tools/background-removal',
    description: 'Remove backgrounds with precision and replace them',
    category: 'Photo Enhancement',
    inputMode: 'edit',
    icon: 'Eraser',
  },
  {
    id: 'ai-retouch',
    name: 'AI Retouch',
    path: '/tools/ai-retouch',
    description: 'Professional photo retouching and enhancement',
    category: 'Photo Enhancement',
    inputMode: 'edit',
    icon: 'Wand2',
  },
  {
    id: 'product-photographer',
    name: 'Product Photographer',
    path: '/tools/product-photographer',
    description: 'Create professional product photography with studio lighting',
    category: 'Professional',
    inputMode: 'edit',
    icon: 'Camera',
  },
  {
    id: 'sketch-pencil-art',
    name: 'Sketch & Pencil Art',
    path: '/tools/sketch-pencil-art',
    description: 'Transform photos into pencil sketches and artistic drawings',
    category: 'Creative Effects',
    inputMode: 'edit',
    icon: 'Pencil',
  },
  {
    id: 'wedding-prewedding-editor',
    name: 'Wedding & Prewedding Editor',
    path: '/tools/wedding-prewedding-editor',
    description: 'Enhance wedding and prewedding photos with romantic effects',
    category: 'Event & Portrait',
    inputMode: 'edit',
    icon: 'Heart',
  },
  {
    id: 'id-photo-booth',
    name: 'ID Photo Booth',
    path: '/tools/id-photo-booth',
    description: 'Create compliant ID photos for passports and documents',
    category: 'Professional',
    inputMode: 'edit',
    icon: 'IdCard',
  },
  {
    id: 'architectural-design-visualizer',
    name: 'Architectural Design Visualizer',
    path: '/tools/architectural-design-visualizer',
    description: 'Visualize architectural designs and interior concepts',
    category: 'Professional',
    inputMode: 'hybrid',
    icon: 'Building2',
  },
  {
    id: 'maternity-photo-editor',
    name: 'Maternity Photo Editor',
    path: '/tools/maternity-photo-editor',
    description: 'Beautiful enhancements for maternity photography',
    category: 'Event & Portrait',
    inputMode: 'edit',
    icon: 'Baby',
  },
  {
    id: 'big-head-caricature-generator',
    name: 'Big Head Caricature Generator',
    path: '/tools/big-head-caricature-generator',
    description: 'Create fun caricatures with exaggerated features',
    category: 'Creative Effects',
    inputMode: 'edit',
    icon: 'Smile',
  },
  {
    id: 'infographic-poster-creator',
    name: 'Infographic Poster Creator',
    path: '/tools/infographic-poster-creator',
    description: 'Design engaging infographics and posters',
    category: 'Design & Branding',
    inputMode: 'generation',
    icon: 'BarChart3',
  },
  {
    id: 'photo-restoration',
    name: 'Photo Restoration',
    path: '/tools/photo-restoration',
    description: 'Restore old and damaged photos to their former glory',
    category: 'Photo Enhancement',
    inputMode: 'edit',
    icon: 'ImagePlus',
  },
  {
    id: 'fashion-model-generator',
    name: 'Fashion Model Generator',
    path: '/tools/fashion-model-generator',
    description: 'Generate fashion model poses and clothing visualizations',
    category: 'Professional',
    inputMode: 'generation',
    icon: 'User',
  },
  {
    id: 'banner-design',
    name: 'Banner Design',
    path: '/tools/banner-design',
    description: 'Create eye-catching banners for web and social media',
    category: 'Design & Branding',
    inputMode: 'generation',
    icon: 'Layout',
  },
  {
    id: 'baby-kids-photo-editor',
    name: 'Baby & Kids Photo Editor',
    path: '/tools/baby-kids-photo-editor',
    description: 'Enhance photos of babies and children with playful effects',
    category: 'Event & Portrait',
    inputMode: 'edit',
    icon: 'Sparkle',
  },
  {
    id: 'religious-event-photo-editor',
    name: 'Religious Event Photo Editor',
    path: '/tools/religious-event-photo-editor',
    description: 'Enhance photos from religious ceremonies and events',
    category: 'Event & Portrait',
    inputMode: 'edit',
    icon: 'Church',
  },
  {
    id: 'graduation-photo-editor',
    name: 'Graduation Photo Editor',
    path: '/tools/graduation-photo-editor',
    description: 'Perfect graduation photos with professional touches',
    category: 'Event & Portrait',
    inputMode: 'edit',
    icon: 'GraduationCap',
  },
  {
    id: 'age-transformation-filter',
    name: 'Age Transformation Filter',
    path: '/tools/age-transformation-filter',
    description: 'See how you look at different ages',
    category: 'Creative Effects',
    inputMode: 'edit',
    icon: 'Clock',
  },
  {
    id: 'magic-eraser',
    name: 'Magic Eraser',
    path: '/tools/magic-eraser',
    description: 'Remove unwanted objects from photos seamlessly',
    category: 'Photo Enhancement',
    inputMode: 'edit',
    icon: 'Trash2',
  },
  {
    id: 'collage-maker',
    name: 'Collage Maker',
    path: '/tools/collage-maker',
    description: 'Create beautiful photo collages with multiple layouts',
    category: 'Creative Effects',
    inputMode: 'hybrid',
    icon: 'Grid3x3',
  },
  {
    id: 'filter-usia-age-filter',
    name: 'Filter Usia (Age Filter)',
    path: '/tools/filter-usia-age-filter',
    description: 'Apply age filters to see younger or older versions',
    category: 'Creative Effects',
    inputMode: 'edit',
    icon: 'Timer',
  },
];

export function getToolById(id: string): ToolDefinition | undefined {
  return TOOLS.find((tool) => tool.id === id);
}

export function getToolsByCategory(category: string): ToolDefinition[] {
  return TOOLS.filter((tool) => tool.category === category);
}
